# this is the configuration file for the sentinela file monitoring service
# changes made in this file will be applied after reboot or daemon reloading

# list of files and directories to be monitored
# if this parameter is altered, please run the rehash function
watchlist = [
  "/etc",
  "/bin",
  "/usr/bin",
  "/sbin",
  "/usr/sbin",
  "/lib",
  "/usr/lib",
  "/usr/include",
  "/boot",
]

# interval (in s) between each check
checkInterval = 600
